
name = "cybercrowd-net"
compatibility_date = "2026-04-25"
[assets] 
directory = "."

[[r2_buckets]]
binding = "ALBUM"
bucket_name = "cybercrowd-album"

[[r2_buckets]]
binding = "GRAPHICS"
bucket_name = "cybercrowd-graphics"

[[r2_buckets]]
binding = "TEASERS"
bucket_name = "cybercrowd-teasers"
