/**
 * src/cyberqr/turnstile-storage.ts
 *
 * CyberCrowd QR4 — CyberQR
 *
 * FIRST ORGAN:
 * TurnstileStorage
 *
 * CyberQR is NOT a QR code.
 * CyberQR is NOT scannable.
 * CyberQR is NOT a payment token.
 * CyberQR is a human-designed four-order identity object.
 *
 * ONE JOB:
 * Hold and verify a CyberQR inside TurnstileStorage using presence lock rules.
 */

export type QR4Order =
  | "public_identity"
  | "private_identity"
  | "value_identity"
  | "continuity_identity";

export type LaneId = string;

export interface IdentitySymbol {
  symbolId: string;

  /**
   * Human-designed symbol name.
   * This is never generated by the system.
   */
  humanName: string;

  /**
   * Human-authored design notes.
   * This is visual recognition language, not machine scanning data.
   */
  designStatement: string;

  /**
   * Must always be false.
   * CyberQR is not a QR code and is not scannable.
   */
  scannable: false;

  /**
   * Must always be true.
   */
  humanDesigned: true;

  /**
   * Optional visual anchor words.
   * Example: ["shield", "crow", "gold line", "black field"]
   */
  visualAnchors: string[];
}

export interface CoverImage {
  coverImageId: string;

  /**
   * Human-selected image reference.
   * This is not a generated QR payload.
   */
  imageRef: string;

  /**
   * Human-readable description of what the cover image represents.
   */
  description: string;

  /**
   * Must remain visual only.
   */
  visualOnly: true;

  /**
   * Must remain false.
   */
  scannable: false;
}

export interface PingGeoLock {
  lockId: string;

  /**
   * The location CyberQR is bound to.
   */
  anchorLocation: {
    latitude: number;
    longitude: number;
  };

  /**
   * Allowed presence radius in meters.
   */
  radiusMeters: number;

  /**
   * Human/presence ping timestamp.
   */
  lastPingAt: string | null;

  /**
   * Mocked presence check.
   * Real GEO/ping can replace this later without changing the CyberQR object.
   */
  isWithinRadius(location: {
    latitude: number;
    longitude: number;
  }): boolean;
}

export interface TurnstileStorageState {
  storageId: string;

  /**
   * CyberQR cannot operate outside TurnstileStorage.
   */
  containsCyberQR: boolean;

  /**
   * Active lane entered by this CyberQR, if any.
   */
  activeLaneId: LaneId | null;

  /**
   * Current presence result.
   */
  presenceVerified: boolean;

  /**
   * Current identity verification result.
   */
  identityVerified: boolean;

  /**
   * CyberQR cannot be duplicated, copied, or transferred.
   */
  duplicateAllowed: false;
  transferAllowed: false;
  copyAllowed: false;

  createdAt: string;
  updatedAt: string;
}

export interface CyberQR {
  cyberQRId: string;

  /**
   * Order 1: Public Identity
   */
  publicIdentity: {
    identityId: string;
    displayName: string;
    publicHandle: string;
  };

  /**
   * Order 2: Private Identity
   */
  privateIdentity: {
    privateIdentityId: string;
    ownerProofRef: string;
    privateLabel: string;
  };

  /**
   * Order 3: Value Identity
   * Ownership, leasing, commitments.
   * This is NOT payment processing.
   */
  valueIdentity: {
    valueIdentityId: string;
    ownershipRefs: string[];
    leaseRefs: string[];
    commitmentRefs: string[];
  };

  /**
   * Order 4: Continuity Identity
   * Binds Orders 1–3 into one identity spine.
   */
  continuityIdentity: {
    continuityId: string;
    spineRef: string;
    orderBinding: [QR4Order, QR4Order, QR4Order, QR4Order];
  };

  /**
   * Human-designed symbol.
   */
  identitySymbol: IdentitySymbol;

  /**
   * Human-selected cover image.
   */
  coverImage: CoverImage;

  /**
   * Presence lock.
   */
  pingGeoLock: PingGeoLock;

  /**
   * CyberQR lives inside TurnstileStorage.
   */
  turnstileStorageId: string;

  /**
   * Hard rules.
   */
  nonScannable: true;
  humanDesigned: true;
  duplicateAllowed: false;
  transferAllowed: false;
  copyAllowed: false;

  createdAt: string;
  updatedAt: string;
}

export class TurnstileStorage {
  private state: TurnstileStorageState;

  constructor(storageId: string) {
    const now = new Date().toISOString();

    this.state = {
      storageId,
      containsCyberQR: false,
      activeLaneId: null,
      presenceVerified: false,
      identityVerified: false,
      duplicateAllowed: false,
      transferAllowed: false,
      copyAllowed: false,
      createdAt: now,
      updatedAt: now
    };
  }

  accept(cyberQR: CyberQR): TurnstileStorageState {
    this.assertCyberQRRules(cyberQR);

    if (cyberQR.turnstileStorageId !== this.state.storageId) {
      throw new Error("CYBERQR_OUTSIDE_TURNSTILE_STORAGE");
    }

    this.state = {
      ...this.state,
      containsCyberQR: true,
      updatedAt: new Date().toISOString()
    };

    return this.readState();
  }

  verifyIdentity(cyberQR: CyberQR): boolean {
    this.assertCyberQRRules(cyberQR);

    const ordersBound =
      cyberQR.continuityIdentity.orderBinding[0] === "public_identity" &&
      cyberQR.continuityIdentity.orderBinding[1] === "private_identity" &&
      cyberQR.continuityIdentity.orderBinding[2] === "value_identity" &&
      cyberQR.continuityIdentity.orderBinding[3] === "continuity_identity";

    const symbolValid =
      cyberQR.identitySymbol.humanDesigned === true &&
      cyberQR.identitySymbol.scannable === false;

    const coverValid =
      cyberQR.coverImage.visualOnly === true &&
      cyberQR.coverImage.scannable === false;

    const storageValid =
      cyberQR.turnstileStorageId === this.state.storageId &&
      this.state.containsCyberQR === true;

    const verified = ordersBound && symbolValid && coverValid && storageValid;

    this.state = {
      ...this.state,
      identityVerified: verified,
      updatedAt: new Date().toISOString()
    };

    return verified;
  }

  enterLane(cyberQR: CyberQR, laneId: LaneId): TurnstileStorageState {
    this.assertCyberQRRules(cyberQR);

    if (!laneId || !laneId.trim()) {
      throw new Error("LANE_ID_REQUIRED");
    }

    const identityVerified = this.verifyIdentity(cyberQR);
    const presenceVerified = cyberQR.pingGeoLock.isWithinRadius(
      cyberQR.pingGeoLock.anchorLocation
    );

    if (!identityVerified) {
      throw new Error("CYBERQR_IDENTITY_NOT_VERIFIED");
    }

    if (!presenceVerified) {
      throw new Error("CYBERQR_PRESENCE_NOT_VERIFIED");
    }

    this.state = {
      ...this.state,
      activeLaneId: laneId.trim(),
      presenceVerified,
      identityVerified,
      updatedAt: new Date().toISOString()
    };

    return this.readState();
  }

  exitLane(cyberQR: CyberQR, laneId: LaneId): TurnstileStorageState {
    this.assertCyberQRRules(cyberQR);

    if (this.state.activeLaneId !== laneId) {
      throw new Error("CYBERQR_NOT_IN_REQUESTED_LANE");
    }

    this.state = {
      ...this.state,
      activeLaneId: null,
      updatedAt: new Date().toISOString()
    };

    return this.readState();
  }

  readState(): TurnstileStorageState {
    return {
      ...this.state,
      duplicateAllowed: false,
      transferAllowed: false,
      copyAllowed: false
    };
  }

  private assertCyberQRRules(cyberQR: CyberQR): void {
    if (!cyberQR) {
      throw new Error("CYBERQR_REQUIRED");
    }

    if (cyberQR.nonScannable !== true) {
      throw new Error("CYBERQR_MUST_BE_NON_SCANNABLE");
    }

    if (cyberQR.humanDesigned !== true) {
      throw new Error("CYBERQR_MUST_BE_HUMAN_DESIGNED");
    }

    if (
      cyberQR.duplicateAllowed !== false ||
      cyberQR.transferAllowed !== false ||
      cyberQR.copyAllowed !== false
    ) {
      throw new Error("CYBERQR_COPY_TRANSFER_DUPLICATE_FORBIDDEN");
    }

    if (cyberQR.identitySymbol.scannable !== false) {
      throw new Error("IDENTITY_SYMBOL_MUST_NOT_BE_SCANNABLE");
    }

    if (cyberQR.identitySymbol.humanDesigned !== true) {
      throw new Error("IDENTITY_SYMBOL_MUST_BE_HUMAN_DESIGNED");
    }

    if (cyberQR.coverImage.scannable !== false) {
      throw new Error("COVER_IMAGE_MUST_NOT_BE_SCANNABLE");
    }
  }
}

export function createMockPingGeoLock(input: {
  lockId: string;
  latitude: number;
  longitude: number;
  radiusMeters: number;
}): PingGeoLock {
  return {
    lockId: input.lockId,
    anchorLocation: {
      latitude: input.latitude,
      longitude: input.longitude
    },
    radiusMeters: input.radiusMeters,
    lastPingAt: new Date().toISOString(),

    isWithinRadius(location) {
      const distance = roughDistanceMeters(
        input.latitude,
        input.longitude,
        location.latitude,
        location.longitude
      );

      return distance <= input.radiusMeters;
    }
  };
}

function roughDistanceMeters(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const metersPerDegree = 111_320;

  const deltaLat = lat1 - lat2;
  const deltaLon = lon1 - lon2;

  return Math.sqrt(deltaLat * deltaLat + deltaLon * deltaLon) * metersPerDegree;
}
